[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[prune]
  go-tests = true
  unused-packages = true
