version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.10

     working_directory: /go/src/github.com/TimWoolford/podrick

     steps:
       - setup_remote_docker

       - checkout

       - run:
           name: build and test
           command: make gotest

       - run:
           name: build image
           command: make build-image

       - run:
           name: push image
           command: |
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             make push-image