version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.9


     working_directory: /go/src/github.com/TimWoolford/podrick

     steps:
       - checkout

       - run:
           name: build
           command: make gotest build-image