apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | indent 4 }}
data:
  config.yaml: |
    versionLabels:
      - version
      - app_version
      - config_version
    appNameLabel: 'app_name'
    labelFile: '/etc/podinfo/labels'
    clusterIdentifier:
      - cluster
    clusterNaming:
      dev: DEV
