apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Chart.Name }}:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.internalPort }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}