apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /namespace
  name: {{ .Chart.Name }}
  labels:
        {{- include "labels" . | indent 4 }}
spec:
  rules:
          {{- range .Values.ingressHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $.Chart.Name }}
              servicePort: 80
        {{- end }}
