kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podrick-view
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podrick
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: podrick-view
  apiGroup: rbac.authorization.k8s.io
