apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app_name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            limits:
              memory: 50Mi
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: podinfo
              mountPath: /etc/podinfo
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /ready
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /ready
              port: {{ .Values.service.internalPort }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations