kind: Secret
type: kubernetes.io/tls
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    {{- include "labels" . | indent 4 }}
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}